/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        background: '#f7f9fc',
        outline: '#916f68',
        'surface-bright': '#f7f9fc',
        tertiary: '#745b00',
        'surface-container-high': '#e6e8eb',
        'on-error-container': '#93000a',
        'surface-container': '#eceef1',
        'on-secondary-fixed-variant': '#5a3482',
        'outline-variant': '#e6bdb5',
        'on-primary-fixed': '#3d0600',
        'primary-fixed': '#ffdad3',
        'error-container': '#ffdad6',
        surface: '#f7f9fc',
        'on-primary-fixed-variant': '#8c1800',
        'secondary-fixed-dim': '#dbb8ff',
        'on-tertiary-fixed-variant': '#584400',
        'on-surface-variant': '#5c4039',
        'on-surface': '#191c1e',
        'surface-container-low': '#f2f4f7',
        'tertiary-fixed-dim': '#f2c000',
        'tertiary-container': '#d1a600',
        'secondary-fixed': '#efdbff',
        error: '#ba1a1a',
        'secondary-container': '#d1a7fe',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#4f3d00',
        'surface-dim': '#d8dadd',
        secondary: '#734c9c',
        'inverse-on-surface': '#eff1f4',
        'on-secondary-fixed': '#2b0052',
        'inverse-primary': '#ffb4a4',
        'primary-container': '#dd3107',
        'surface-variant': '#e0e3e6',
        primary: '#b22200',
        'on-tertiary-fixed': '#241a00',
        'tertiary-fixed': '#ffe08d',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e0e3e6',
        'primary-fixed-dim': '#ffb4a4',
        'on-background': '#191c1e',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-secondary-container': '#5c3785',
        'surface-tint': '#b72300',
        'inverse-surface': '#2d3133',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'margin-desktop': '64px',
        'container-max': '1200px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        mono: ['"Space Mono"', 'monospace'],
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'display-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
      },
      boxShadow: {
        pixel: '4px 4px 0px 0px rgba(25,28,30,1)',
        'pixel-sm': '2px 2px 0px 0px rgba(25,28,30,1)',
        'pixel-lg': '8px 8px 0px 0px rgba(25,28,30,1)',
        'pixel-up': '0px -4px 0px 0px rgba(25,28,30,1)',
      },
    },
  },
  plugins: [],
};
