services:
  mongo:
    image: mongo:7
    container_name: portfolio-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ttoavina
      MONGO_INITDB_ROOT_PASSWORD: ttoavina
      MONGO_INITDB_DATABASE: portfolio
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
